### ISSUE TITLE
Error running dev environment

### ISSUE THREAD

**Issue by kierangilliam** [ryands17/serverless-prisma#13]
First off, thanks for the work on this project. You did a great job creating this clean and well-structured template.

I'm having issues running the starter code, unedited, in a dev environment. I get the following error after running `yarn dev` after visiting `http://localhost:3000/dev/graphql`.

`Error: Root typing path /Users/.../serverless-prisma/dist/context.ts for the type context does not exist`

Any ideas on how to fix this issue?

**Comment by kierangilliam** [comment]
To fix this I did the following

In `schema.ts` change the line to read `module: join(__dirname, 'context.js'),` under `contextType:`.

Add `rm -rf dist && ...` at the beginning of the `dev` command.

edit: This worked for a few runs but as I started to add more to the schema, I got the same error as above but for context.js

**Comment by ryands17** [comment]
Hey @kierangilliam 👋 
I'm glad you liked the setup :)

The reason this warning shows up is that Nexus in development needs to read the typescript types and as we first transpile from TS to JS for Serverless, it complains that it cannot find the TS file for the types. Nexus in development just requires that to be set which is why if you run it via `ts-node`, it doesn't give that error. In this example that I have created:

https://github.com/ryands17/nexus-auth

You will not find the above warning. Also this is just a warning and it won't be visible when you deploy this in production if you set the `NODE_ENV` to `production` in the `.env` file. Below are the Cloudwatch logs after deployment:

![image](https://user-images.githubusercontent.com/19697099/105003306-80d50c80-5a58-11eb-9118-d9d592fe1f7d.png)


Let me know if you have any other queries :)
